# Generated by Django 3.2.6 on 2021-08-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacrificing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
